name: Build TKA Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Create Firebase google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}
        run: |
          if [ -z "$GOOGLE_SERVICES_JSON" ]; then
            echo "ERROR: FIREBASE_GOOGLE_SERVICES_JSON secret belum dibuat."
            exit 1
          fi

          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TKA-2026-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
