name: Build Flutter APK

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil source code dari repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 3. Cek versi Flutter
      - name: Flutter Doctor
        run: flutter doctor -v

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Build APK Release
      - name: Build APK
        run: flutter build apk --release

      # 6. Simpan APK sebagai artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: futureee-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
